void SynchronizeDis(int type){
  SynchronizeInfo(type);
  synchronize(0,0,32,32);
}
void SynchronizeInfo(int progress){
    screenCleanA();
    Heltec.display->setFont(ArialMT_Plain_10);
    String strinfo1="Unknown";
    String strinfo2="Unknown";
    if(progress==1){
      strinfo1="Time";
      strinfo2="Updating...";
    }
    if(progress==2){
      strinfo1="Weather";
      strinfo2="Updating...";
    }
    drawRectdotI(36,0,128-37,32,3);
    Heltec.display->setTextAlignment(TEXT_ALIGN_CENTER_BOTH);
    Heltec.display->drawString(screencenterX,screencenterY-5,strinfo1); 
    Heltec.display->drawString(screencenterX,screencenterY+5,strinfo2);
    Heltec.display->display();
}
void synchronize(int xpos,int ypos,int iwidth,int iheight){
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize00);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize01);    
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize02);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize03);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize04);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize05);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize06);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize07);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize08);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize09);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize10);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize11);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize12);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize13);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize14);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize15);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize16);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize17);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize18);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize19);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize20);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize21);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize22);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize23);
    
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize24);
    Heltec.display->display();
    delay(refreshtime);    
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize25);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize26);
    Heltec.display->display();
    delay(refreshtime);
    screenClean(xpos,ypos,iwidth,iheight);
    Heltec.display->drawXbm(xpos, ypos, iwidth, iheight, synchronize27);
    Heltec.display->display();
    delay(refreshtime);
}
