void WeatherNowInfo(){
    screenCleanA();
    Heltec.display->setFont(ArialMT_Plain_10);
    Heltec.display->setTextAlignment(TEXT_ALIGN_CENTER_BOTH);
    drawRectdotO(36,0,128-37,32,3);
    Heltec.display->drawString(screencenterX,screencenterY-5,weathernow); 
    Heltec.display->drawString(screencenterX,screencenterY+5,"Temp:"+tempnow+"°C");
    Heltec.display->display();
}
void WeatherNowDis(){
    if(WiFi.status() != WL_CONNECTED){
      WeatherNowInfo();
      puzzled(0,0,32,32);
      Serial.println(F("No Internet Connect!"));
      Serial.flush();
      return;
    }
    UpdateWeatherNow();
    WeatherNowInfo();
    if(weathernow=="null"){
      puzzled(0,0,32,32);
    }//获取不到天气信息
    if(weathercode==0||weathercode==1||weathercode==38){
      sunny(0,0,32,32);
    }
    if(weathercode==4||weathercode==5||weathercode==6||weathercode==7||weathercode==8||weathercode==9){
      cloudy(0,0,32,32);
    }
    if(weathercode==10){
      shower(0,0,32,32);
    }   
    if(weathercode==11||weathercode==12){
      thunderrain(0,0,32,32);
    } 
    if(weathercode==13||weathercode==14){
      lightrain(0,0,32,32);
    } 
    if(weathercode==15||weathercode==16||weathercode==17||weathercode==18){
      heavyrain(0,0,32,32);
    }
    if(weathercode==19||weathercode==20||weathercode==21||weathercode==22||weathercode==23){
      lightsnow(0,0,32,32);
    }
    if(weathercode==24||weathercode==25||weathercode==37){
      heavysnow(0,0,32,32);
    }
    if(weathercode==26||weathercode==27||weathercode==28||weathercode==29||weathercode==30||weathercode==31){
      if(hour()>=18){
        nightfog(0,0,32,32);
      }else{
        dayhaze(0,0,32,32);
      }
    }
    if(weathercode==32||weathercode==33||weathercode==34||weathercode==35||weathercode==36){
      windy(0,0,32,32);
    }
}
